//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum AbstractNodeType {
  ANT_UNKNOWN,
  ANT_ATOM,
  ANT_OBJECT,
  ANT_PROPERTY,
  ANT_IMPORT,
  ANT_VARIABLE_SET,
  ANT_VARIABLE_ACCESS
}

}
