//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum btRigidBodyFlags {
  BT_DISABLE_WORLD_GRAVITY = 1,
  BT_ENABLE_GYROSCOPIC_FORCE_EXPLICIT = 2,
  BT_ENABLE_GYROSCOPIC_FORCE_IMPLICIT_WORLD = 4,
  BT_ENABLE_GYROSCOPIC_FORCE_IMPLICIT_BODY = 8,
  BT_ENABLE_GYROPSCOPIC_FORCE = BT_ENABLE_GYROSCOPIC_FORCE_IMPLICIT_BODY
}

}
