//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class btRigidBody : btCollisionObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal btRigidBody(global::System.IntPtr cPtr, bool cMemoryOwn) : base(OgreBulletPINVOKE.btRigidBody_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btRigidBody obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgreBulletPINVOKE.delete_btRigidBody(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public class btRigidBodyConstructionInfo : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal btRigidBodyConstructionInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(btRigidBodyConstructionInfo obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~btRigidBodyConstructionInfo() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            OgreBulletPINVOKE.delete_btRigidBody_btRigidBodyConstructionInfo(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public float m_mass {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_mass_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_mass_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public SWIGTYPE_p_btMotionState m_motionState {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_motionState_set(swigCPtr, SWIGTYPE_p_btMotionState.getCPtr(value));
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_motionState_get(swigCPtr);
        SWIGTYPE_p_btMotionState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btMotionState(cPtr, false);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public SWIGTYPE_p_btTransform m_startWorldTransform {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_startWorldTransform_set(swigCPtr, SWIGTYPE_p_btTransform.getCPtr(value));
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        SWIGTYPE_p_btTransform ret = new SWIGTYPE_p_btTransform(OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_startWorldTransform_get(swigCPtr), true);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public SWIGTYPE_p_btCollisionShape m_collisionShape {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_collisionShape_set(swigCPtr, SWIGTYPE_p_btCollisionShape.getCPtr(value));
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_collisionShape_get(swigCPtr);
        SWIGTYPE_p_btCollisionShape ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btCollisionShape(cPtr, false);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public btVector3 m_localInertia {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_localInertia_set(swigCPtr, btVector3.getCPtr(value));
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_localInertia_get(swigCPtr);
        btVector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new btVector3(cPtr, false);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_linearDamping {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_linearDamping_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_linearDamping_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_angularDamping {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_angularDamping_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_angularDamping_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_friction {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_friction_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_friction_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_rollingFriction {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_rollingFriction_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_rollingFriction_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_spinningFriction {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_spinningFriction_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_spinningFriction_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_restitution {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_restitution_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_restitution_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_linearSleepingThreshold {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_linearSleepingThreshold_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_linearSleepingThreshold_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_angularSleepingThreshold {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_angularSleepingThreshold_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_angularSleepingThreshold_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public bool m_additionalDamping {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalDamping_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        bool ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalDamping_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_additionalDampingFactor {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalDampingFactor_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalDampingFactor_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_additionalLinearDampingThresholdSqr {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalLinearDampingThresholdSqr_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalLinearDampingThresholdSqr_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_additionalAngularDampingThresholdSqr {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalAngularDampingThresholdSqr_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalAngularDampingThresholdSqr_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public float m_additionalAngularDampingFactor {
      set {
        OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalAngularDampingFactor_set(swigCPtr, value);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        float ret = OgreBulletPINVOKE.btRigidBody_btRigidBodyConstructionInfo_m_additionalAngularDampingFactor_get(swigCPtr);
        if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public btRigidBodyConstructionInfo(float mass, SWIGTYPE_p_btMotionState motionState, SWIGTYPE_p_btCollisionShape collisionShape, btVector3 localInertia) : this(OgreBulletPINVOKE.new_btRigidBody_btRigidBodyConstructionInfo__SWIG_0(mass, SWIGTYPE_p_btMotionState.getCPtr(motionState), SWIGTYPE_p_btCollisionShape.getCPtr(collisionShape), btVector3.getCPtr(localInertia)), true) {
      if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public btRigidBodyConstructionInfo(float mass, SWIGTYPE_p_btMotionState motionState, SWIGTYPE_p_btCollisionShape collisionShape) : this(OgreBulletPINVOKE.new_btRigidBody_btRigidBodyConstructionInfo__SWIG_1(mass, SWIGTYPE_p_btMotionState.getCPtr(motionState), SWIGTYPE_p_btCollisionShape.getCPtr(collisionShape)), true) {
      if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    }
  
  }

  public btRigidBody(btRigidBody.btRigidBodyConstructionInfo constructionInfo) : this(OgreBulletPINVOKE.new_btRigidBody__SWIG_0(btRigidBody.btRigidBodyConstructionInfo.getCPtr(constructionInfo)), true) {
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btRigidBody(float mass, SWIGTYPE_p_btMotionState motionState, SWIGTYPE_p_btCollisionShape collisionShape, btVector3 localInertia) : this(OgreBulletPINVOKE.new_btRigidBody__SWIG_1(mass, SWIGTYPE_p_btMotionState.getCPtr(motionState), SWIGTYPE_p_btCollisionShape.getCPtr(collisionShape), btVector3.getCPtr(localInertia)), true) {
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btRigidBody(float mass, SWIGTYPE_p_btMotionState motionState, SWIGTYPE_p_btCollisionShape collisionShape) : this(OgreBulletPINVOKE.new_btRigidBody__SWIG_2(mass, SWIGTYPE_p_btMotionState.getCPtr(motionState), SWIGTYPE_p_btCollisionShape.getCPtr(collisionShape)), true) {
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void proceedToTransform(SWIGTYPE_p_btTransform newTrans) {
    OgreBulletPINVOKE.btRigidBody_proceedToTransform(swigCPtr, SWIGTYPE_p_btTransform.getCPtr(newTrans));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public static btRigidBody upcast(btCollisionObject colObj) {
    global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_upcast__SWIG_0(btCollisionObject.getCPtr(colObj));
    btRigidBody ret = (cPtr == global::System.IntPtr.Zero) ? null : new btRigidBody(cPtr, false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void predictIntegratedTransform(float step, SWIGTYPE_p_btTransform predictedTransform) {
    OgreBulletPINVOKE.btRigidBody_predictIntegratedTransform(swigCPtr, step, SWIGTYPE_p_btTransform.getCPtr(predictedTransform));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void saveKinematicState(float step) {
    OgreBulletPINVOKE.btRigidBody_saveKinematicState(swigCPtr, step);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyGravity() {
    OgreBulletPINVOKE.btRigidBody_applyGravity(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void clearGravity() {
    OgreBulletPINVOKE.btRigidBody_clearGravity(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setGravity(btVector3 acceleration) {
    OgreBulletPINVOKE.btRigidBody_setGravity(swigCPtr, btVector3.getCPtr(acceleration));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btVector3 getGravity() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getGravity(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDamping(float lin_damping, float ang_damping) {
    OgreBulletPINVOKE.btRigidBody_setDamping(swigCPtr, lin_damping, ang_damping);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getLinearDamping() {
    float ret = OgreBulletPINVOKE.btRigidBody_getLinearDamping(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getAngularDamping() {
    float ret = OgreBulletPINVOKE.btRigidBody_getAngularDamping(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getLinearSleepingThreshold() {
    float ret = OgreBulletPINVOKE.btRigidBody_getLinearSleepingThreshold(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getAngularSleepingThreshold() {
    float ret = OgreBulletPINVOKE.btRigidBody_getAngularSleepingThreshold(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void applyDamping(float timeStep) {
    OgreBulletPINVOKE.btRigidBody_applyDamping(swigCPtr, timeStep);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public new SWIGTYPE_p_btCollisionShape getCollisionShape() {
    global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_getCollisionShape__SWIG_0(swigCPtr);
    SWIGTYPE_p_btCollisionShape ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btCollisionShape(cPtr, false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setMassProps(float mass, btVector3 inertia) {
    OgreBulletPINVOKE.btRigidBody_setMassProps(swigCPtr, mass, btVector3.getCPtr(inertia));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btVector3 getLinearFactor() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getLinearFactor(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setLinearFactor(btVector3 linearFactor) {
    OgreBulletPINVOKE.btRigidBody_setLinearFactor(swigCPtr, btVector3.getCPtr(linearFactor));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getInvMass() {
    float ret = OgreBulletPINVOKE.btRigidBody_getInvMass(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getMass() {
    float ret = OgreBulletPINVOKE.btRigidBody_getMass(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_btMatrix3x3 getInvInertiaTensorWorld() {
    SWIGTYPE_p_btMatrix3x3 ret = new SWIGTYPE_p_btMatrix3x3(OgreBulletPINVOKE.btRigidBody_getInvInertiaTensorWorld(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void integrateVelocities(float step) {
    OgreBulletPINVOKE.btRigidBody_integrateVelocities(swigCPtr, step);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setCenterOfMassTransform(SWIGTYPE_p_btTransform xform) {
    OgreBulletPINVOKE.btRigidBody_setCenterOfMassTransform(swigCPtr, SWIGTYPE_p_btTransform.getCPtr(xform));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyCentralForce(btVector3 force) {
    OgreBulletPINVOKE.btRigidBody_applyCentralForce(swigCPtr, btVector3.getCPtr(force));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btVector3 getTotalForce() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getTotalForce(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 getTotalTorque() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getTotalTorque(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 getInvInertiaDiagLocal() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getInvInertiaDiagLocal(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setInvInertiaDiagLocal(btVector3 diagInvInertia) {
    OgreBulletPINVOKE.btRigidBody_setInvInertiaDiagLocal(swigCPtr, btVector3.getCPtr(diagInvInertia));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSleepingThresholds(float linear, float angular) {
    OgreBulletPINVOKE.btRigidBody_setSleepingThresholds(swigCPtr, linear, angular);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyTorque(btVector3 torque) {
    OgreBulletPINVOKE.btRigidBody_applyTorque(swigCPtr, btVector3.getCPtr(torque));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyForce(btVector3 force, btVector3 rel_pos) {
    OgreBulletPINVOKE.btRigidBody_applyForce(swigCPtr, btVector3.getCPtr(force), btVector3.getCPtr(rel_pos));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyCentralImpulse(btVector3 impulse) {
    OgreBulletPINVOKE.btRigidBody_applyCentralImpulse(swigCPtr, btVector3.getCPtr(impulse));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyTorqueImpulse(btVector3 torque) {
    OgreBulletPINVOKE.btRigidBody_applyTorqueImpulse(swigCPtr, btVector3.getCPtr(torque));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyImpulse(btVector3 impulse, btVector3 rel_pos) {
    OgreBulletPINVOKE.btRigidBody_applyImpulse(swigCPtr, btVector3.getCPtr(impulse), btVector3.getCPtr(rel_pos));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyPushImpulse(btVector3 impulse, btVector3 rel_pos) {
    OgreBulletPINVOKE.btRigidBody_applyPushImpulse(swigCPtr, btVector3.getCPtr(impulse), btVector3.getCPtr(rel_pos));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btVector3 getPushVelocity() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getPushVelocity(swigCPtr), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 getTurnVelocity() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getTurnVelocity(swigCPtr), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPushVelocity(btVector3 v) {
    OgreBulletPINVOKE.btRigidBody_setPushVelocity(swigCPtr, btVector3.getCPtr(v));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setTurnVelocity(btVector3 v) {
    OgreBulletPINVOKE.btRigidBody_setTurnVelocity(swigCPtr, btVector3.getCPtr(v));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyCentralPushImpulse(btVector3 impulse) {
    OgreBulletPINVOKE.btRigidBody_applyCentralPushImpulse(swigCPtr, btVector3.getCPtr(impulse));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void applyTorqueTurnImpulse(btVector3 torque) {
    OgreBulletPINVOKE.btRigidBody_applyTorqueTurnImpulse(swigCPtr, btVector3.getCPtr(torque));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void clearForces() {
    OgreBulletPINVOKE.btRigidBody_clearForces(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateInertiaTensor() {
    OgreBulletPINVOKE.btRigidBody_updateInertiaTensor(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btVector3 getCenterOfMassPosition() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getCenterOfMassPosition(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_btQuaternion getOrientation() {
    SWIGTYPE_p_btQuaternion ret = new SWIGTYPE_p_btQuaternion(OgreBulletPINVOKE.btRigidBody_getOrientation(swigCPtr), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_btTransform getCenterOfMassTransform() {
    SWIGTYPE_p_btTransform ret = new SWIGTYPE_p_btTransform(OgreBulletPINVOKE.btRigidBody_getCenterOfMassTransform(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 getLinearVelocity() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getLinearVelocity(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 getAngularVelocity() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getAngularVelocity(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setLinearVelocity(btVector3 lin_vel) {
    OgreBulletPINVOKE.btRigidBody_setLinearVelocity(swigCPtr, btVector3.getCPtr(lin_vel));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setAngularVelocity(btVector3 ang_vel) {
    OgreBulletPINVOKE.btRigidBody_setAngularVelocity(swigCPtr, btVector3.getCPtr(ang_vel));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btVector3 getVelocityInLocalPoint(btVector3 rel_pos) {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getVelocityInLocalPoint(swigCPtr, btVector3.getCPtr(rel_pos)), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 getPushVelocityInLocalPoint(btVector3 rel_pos) {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getPushVelocityInLocalPoint(swigCPtr, btVector3.getCPtr(rel_pos)), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void translate(btVector3 v) {
    OgreBulletPINVOKE.btRigidBody_translate(swigCPtr, btVector3.getCPtr(v));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void getAabb(btVector3 aabbMin, btVector3 aabbMax) {
    OgreBulletPINVOKE.btRigidBody_getAabb(swigCPtr, btVector3.getCPtr(aabbMin), btVector3.getCPtr(aabbMax));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public float computeImpulseDenominator(btVector3 pos, btVector3 normal) {
    float ret = OgreBulletPINVOKE.btRigidBody_computeImpulseDenominator(swigCPtr, btVector3.getCPtr(pos), btVector3.getCPtr(normal));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float computeAngularImpulseDenominator(btVector3 axis) {
    float ret = OgreBulletPINVOKE.btRigidBody_computeAngularImpulseDenominator(swigCPtr, btVector3.getCPtr(axis));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void updateDeactivation(float timeStep) {
    OgreBulletPINVOKE.btRigidBody_updateDeactivation(swigCPtr, timeStep);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool wantsSleeping() {
    bool ret = OgreBulletPINVOKE.btRigidBody_wantsSleeping(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_btBroadphaseProxy getBroadphaseProxy() {
    global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_getBroadphaseProxy__SWIG_0(swigCPtr);
    SWIGTYPE_p_btBroadphaseProxy ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btBroadphaseProxy(cPtr, false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setNewBroadphaseProxy(SWIGTYPE_p_btBroadphaseProxy broadphaseProxy) {
    OgreBulletPINVOKE.btRigidBody_setNewBroadphaseProxy(swigCPtr, SWIGTYPE_p_btBroadphaseProxy.getCPtr(broadphaseProxy));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_btMotionState getMotionState() {
    global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_getMotionState__SWIG_0(swigCPtr);
    SWIGTYPE_p_btMotionState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btMotionState(cPtr, false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setMotionState(SWIGTYPE_p_btMotionState motionState) {
    OgreBulletPINVOKE.btRigidBody_setMotionState(swigCPtr, SWIGTYPE_p_btMotionState.getCPtr(motionState));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public int m_contactSolverType {
    set {
      OgreBulletPINVOKE.btRigidBody_m_contactSolverType_set(swigCPtr, value);
      if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = OgreBulletPINVOKE.btRigidBody_m_contactSolverType_get(swigCPtr);
      if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int m_frictionSolverType {
    set {
      OgreBulletPINVOKE.btRigidBody_m_frictionSolverType_set(swigCPtr, value);
      if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = OgreBulletPINVOKE.btRigidBody_m_frictionSolverType_get(swigCPtr);
      if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public void setAngularFactor(btVector3 angFac) {
    OgreBulletPINVOKE.btRigidBody_setAngularFactor__SWIG_0(swigCPtr, btVector3.getCPtr(angFac));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setAngularFactor(float angFac) {
    OgreBulletPINVOKE.btRigidBody_setAngularFactor__SWIG_1(swigCPtr, angFac);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public btVector3 getAngularFactor() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getAngularFactor(swigCPtr), false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isInWorld() {
    bool ret = OgreBulletPINVOKE.btRigidBody_isInWorld(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addConstraintRef(SWIGTYPE_p_btTypedConstraint c) {
    OgreBulletPINVOKE.btRigidBody_addConstraintRef(swigCPtr, SWIGTYPE_p_btTypedConstraint.getCPtr(c));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeConstraintRef(SWIGTYPE_p_btTypedConstraint c) {
    OgreBulletPINVOKE.btRigidBody_removeConstraintRef(swigCPtr, SWIGTYPE_p_btTypedConstraint.getCPtr(c));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_btTypedConstraint getConstraintRef(int index) {
    global::System.IntPtr cPtr = OgreBulletPINVOKE.btRigidBody_getConstraintRef(swigCPtr, index);
    SWIGTYPE_p_btTypedConstraint ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_btTypedConstraint(cPtr, false);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getNumConstraintRefs() {
    int ret = OgreBulletPINVOKE.btRigidBody_getNumConstraintRefs(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setFlags(int flags) {
    OgreBulletPINVOKE.btRigidBody_setFlags(swigCPtr, flags);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getFlags() {
    int ret = OgreBulletPINVOKE.btRigidBody_getFlags(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 computeGyroscopicImpulseImplicit_World(float dt) {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_computeGyroscopicImpulseImplicit_World(swigCPtr, dt), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 computeGyroscopicImpulseImplicit_Body(float step) {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_computeGyroscopicImpulseImplicit_Body(swigCPtr, step), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 computeGyroscopicForceExplicit(float maxGyroscopicForce) {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_computeGyroscopicForceExplicit(swigCPtr, maxGyroscopicForce), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public btVector3 getLocalInertia() {
    btVector3 ret = new btVector3(OgreBulletPINVOKE.btRigidBody_getLocalInertia(swigCPtr), true);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int calculateSerializeBufferSize() {
    int ret = OgreBulletPINVOKE.btRigidBody_calculateSerializeBufferSize(swigCPtr);
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string serialize(global::System.IntPtr dataBuffer, SWIGTYPE_p_btSerializer serializer) {
    string ret = OgreBulletPINVOKE.btRigidBody_serialize(swigCPtr, dataBuffer, SWIGTYPE_p_btSerializer.getCPtr(serializer));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void serializeSingleObject(SWIGTYPE_p_btSerializer serializer) {
    OgreBulletPINVOKE.btRigidBody_serializeSingleObject(swigCPtr, SWIGTYPE_p_btSerializer.getCPtr(serializer));
    if (OgreBulletPINVOKE.SWIGPendingException.Pending) throw OgreBulletPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
