//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum CompareFunction {
  CMPF_ALWAYS_FAIL,
  CMPF_ALWAYS_PASS,
  CMPF_LESS,
  CMPF_LESS_EQUAL,
  CMPF_EQUAL,
  CMPF_NOT_EQUAL,
  CMPF_GREATER_EQUAL,
  CMPF_GREATER
}

}
