//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class CreateGpuProgramScriptCompilerEvent : ScriptCompilerEvent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CreateGpuProgramScriptCompilerEvent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CreateGpuProgramScriptCompilerEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrePINVOKE.delete_CreateGpuProgramScriptCompilerEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public string mFile {
    set {
      OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mFile_set(swigCPtr, value);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mFile_get(swigCPtr);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mName {
    set {
      OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mName_set(swigCPtr, value);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mName_get(swigCPtr);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mResourceGroup {
    set {
      OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mResourceGroup_set(swigCPtr, value);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mResourceGroup_get(swigCPtr);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mSource {
    set {
      OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mSource_set(swigCPtr, value);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mSource_get(swigCPtr);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string mSyntax {
    set {
      OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mSyntax_set(swigCPtr, value);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mSyntax_get(swigCPtr);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public GpuProgramType mProgramType {
    set {
      OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mProgramType_set(swigCPtr, (int)value);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      GpuProgramType ret = (GpuProgramType)OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_mProgramType_get(swigCPtr);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static string eventType {
    set {
      OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_eventType_set(value);
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = OgrePINVOKE.CreateGpuProgramScriptCompilerEvent_eventType_get();
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public CreateGpuProgramScriptCompilerEvent(string file, string name, string resourceGroup, string source, string syntax, GpuProgramType programType) : this(OgrePINVOKE.new_CreateGpuProgramScriptCompilerEvent(file, name, resourceGroup, source, syntax, (int)programType), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
