//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum InstanceManagerFlags {
  IM_USE16BIT = 0x0001,
  IM_VTFBESTFIT = 0x0002,
  IM_VTFBONEMATRIXLOOKUP = 0x0004,
  IM_USEBONEDUALQUATERNIONS = 0x0008,
  IM_USEONEWEIGHT = 0x0010,
  IM_FORCEONEWEIGHT = 0x0020,
  IM_USEALL = IM_USE16BIT|IM_VTFBESTFIT|IM_USEONEWEIGHT
}

}
