//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum MeshVersion {
  MESH_VERSION_LATEST,
  MESH_VERSION_1_10,
  MESH_VERSION_1_8,
  MESH_VERSION_1_7,
  MESH_VERSION_1_4,
  MESH_VERSION_1_0,
  MESH_VERSION_LEGACY
}

}
