//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class PanelOverlayElementPtr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PanelOverlayElementPtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PanelOverlayElementPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PanelOverlayElementPtr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgreOverlayPINVOKE.delete_PanelOverlayElementPtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PanelOverlayElementPtr(SWIGTYPE_p_std__nullptr_t arg0) : this(OgreOverlayPINVOKE.new_PanelOverlayElementPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true) {
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public PanelOverlayElementPtr() : this(OgreOverlayPINVOKE.new_PanelOverlayElementPtr__SWIG_1(), true) {
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public PanelOverlayElementPtr(PanelOverlayElementPtr r) : this(OgreOverlayPINVOKE.new_PanelOverlayElementPtr__SWIG_2(PanelOverlayElementPtr.getCPtr(r)), true) {
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public PanelOverlayElement __deref__() {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr___deref__(swigCPtr);
    PanelOverlayElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new PanelOverlayElement(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void initialise() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_initialise(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _releaseManualHardwareResources() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__releaseManualHardwareResources(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _restoreManualHardwareResources() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__restoreManualHardwareResources(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setTiling(float x, float y, ushort layer) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setTiling__SWIG_0(swigCPtr, x, y, layer);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setTiling(float x, float y) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setTiling__SWIG_1(swigCPtr, x, y);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getTileX(ushort layer) {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getTileX__SWIG_0(swigCPtr, layer);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getTileX() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getTileX__SWIG_1(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getTileY(ushort layer) {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getTileY__SWIG_0(swigCPtr, layer);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getTileY() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getTileY__SWIG_1(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setUV(float u1, float v1, float u2, float v2) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setUV(swigCPtr, u1, v1, u2, v2);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void getUV(SWIGTYPE_p_float u1, SWIGTYPE_p_float v1, SWIGTYPE_p_float u2, SWIGTYPE_p_float v2) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_getUV(swigCPtr, SWIGTYPE_p_float.getCPtr(u1), SWIGTYPE_p_float.getCPtr(v1), SWIGTYPE_p_float.getCPtr(u2), SWIGTYPE_p_float.getCPtr(v2));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setTransparent(bool isTransparent) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setTransparent(swigCPtr, isTransparent);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isTransparent() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_isTransparent(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getTypeName() {
    string ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getTypeName(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void getRenderOperation(RenderOperation op) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_getRenderOperation(swigCPtr, RenderOperation.getCPtr(op));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _updateRenderQueue(RenderQueue queue) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__updateRenderQueue(swigCPtr, RenderQueue.getCPtr(queue));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addChild(OverlayElement elem) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_addChild(swigCPtr, OverlayElement.getCPtr(elem));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addChildImpl(OverlayElement elem) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_addChildImpl__SWIG_0(swigCPtr, OverlayElement.getCPtr(elem));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addChildImpl(OverlayContainer cont) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_addChildImpl__SWIG_1(swigCPtr, OverlayContainer.getCPtr(cont));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeChild(string name) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_removeChild(swigCPtr, name);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public OverlayElement getChild(string name) {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_getChild(swigCPtr, name);
    OverlayElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new OverlayElement(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void _addChild(OverlayElement elem) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__addChild(swigCPtr, OverlayElement.getCPtr(elem));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _removeChild(OverlayElement elem) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__removeChild__SWIG_0(swigCPtr, OverlayElement.getCPtr(elem));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _removeChild(string name) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__removeChild__SWIG_1(swigCPtr, name);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__mapT_std__string_Ogre__OverlayElement_p_std__lessT_std__string_t_t getChildren() {
    SWIGTYPE_p_std__mapT_std__string_Ogre__OverlayElement_p_std__lessT_std__string_t_t ret = new SWIGTYPE_p_std__mapT_std__string_Ogre__OverlayElement_p_std__lessT_std__string_t_t(OgreOverlayPINVOKE.PanelOverlayElementPtr_getChildren(swigCPtr), false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void _positionsOutOfDate() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__positionsOutOfDate(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _update() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__update(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public ushort _notifyZOrder(ushort newZOrder) {
    ushort ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__notifyZOrder(swigCPtr, newZOrder);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void _notifyViewport() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__notifyViewport(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _notifyWorldTransforms(Matrix4 xform) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__notifyWorldTransforms(swigCPtr, Matrix4.getCPtr(xform));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _notifyParent(OverlayContainer parent, Overlay overlay) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__notifyParent(swigCPtr, OverlayContainer.getCPtr(parent), Overlay.getCPtr(overlay));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isContainer() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_isContainer(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isChildrenProcessEvents() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_isChildrenProcessEvents(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setChildrenProcessEvents(bool val) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setChildrenProcessEvents(swigCPtr, val);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public OverlayElement findElementAt(float x, float y) {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_findElementAt(swigCPtr, x, y);
    OverlayElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new OverlayElement(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void copyFromTemplate(OverlayElement templateOverlay) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_copyFromTemplate(swigCPtr, OverlayElement.getCPtr(templateOverlay));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public OverlayElement clone(string instanceName) {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_clone(swigCPtr, instanceName);
    OverlayElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new OverlayElement(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string DEFAULT_RESOURCE_GROUP {
    get {
      string ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_DEFAULT_RESOURCE_GROUP_get(swigCPtr);
      if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string getName() {
    string ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getName(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void show() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_show(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void hide() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_hide(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setVisible(bool visible) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setVisible(swigCPtr, visible);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isVisible() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_isVisible(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isEnabled() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_isEnabled(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setEnabled(bool b) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setEnabled(swigCPtr, b);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setDimensions(float width, float height) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setDimensions(swigCPtr, width, height);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setPosition(float left, float top) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setPosition(swigCPtr, left, top);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setWidth(float width) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setWidth(swigCPtr, width);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getWidth() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getWidth(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setHeight(float height) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setHeight(swigCPtr, height);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getHeight() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getHeight(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setLeft(float left) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setLeft(swigCPtr, left);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getLeft() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getLeft(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setTop(float Top) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setTop(swigCPtr, Top);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getTop() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getTop(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float _getLeft() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getLeft(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float _getTop() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getTop(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float _getWidth() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getWidth(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float _getHeight() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getHeight(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void _setLeft(float left) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__setLeft(swigCPtr, left);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _setTop(float top) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__setTop(swigCPtr, top);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _setWidth(float width) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__setWidth(swigCPtr, width);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _setHeight(float height) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__setHeight(swigCPtr, height);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _setPosition(float left, float top) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__setPosition(swigCPtr, left, top);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _setDimensions(float width, float height) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__setDimensions(swigCPtr, width, height);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getMaterialName() {
    string ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getMaterialName(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setMaterial(MaterialPtr mat) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setMaterial(swigCPtr, MaterialPtr.getCPtr(mat));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setMaterialName(string matName, string group) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setMaterialName__SWIG_0(swigCPtr, matName, group);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setMaterialName(string matName) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setMaterialName__SWIG_1(swigCPtr, matName);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public MaterialPtr getMaterial() {
    MaterialPtr ret = new MaterialPtr(OgreOverlayPINVOKE.PanelOverlayElementPtr_getMaterial(swigCPtr), false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void getWorldTransforms(Matrix4 xform) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_getWorldTransforms(swigCPtr, Matrix4.getCPtr(xform));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void _updateFromParent() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__updateFromParent(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public float _getDerivedLeft() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getDerivedLeft(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float _getDerivedTop() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getDerivedTop(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float _getRelativeWidth() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getRelativeWidth(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float _getRelativeHeight() {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getRelativeHeight(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void _getClippingRegion(FloatRect clippingRegion) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__getClippingRegion(swigCPtr, FloatRect.getCPtr(clippingRegion));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void visitRenderables(Renderable.Visitor visitor, bool debugRenderables) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_visitRenderables__SWIG_0(swigCPtr, Renderable.Visitor.getCPtr(visitor), debugRenderables);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void visitRenderables(Renderable.Visitor visitor) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_visitRenderables__SWIG_1(swigCPtr, Renderable.Visitor.getCPtr(visitor));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setCaption(string text) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setCaption(swigCPtr, text);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getCaption() {
    string ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getCaption(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setColour(ColourValue col) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setColour(swigCPtr, ColourValue.getCPtr(col));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public ColourValue getColour() {
    ColourValue ret = new ColourValue(OgreOverlayPINVOKE.PanelOverlayElementPtr_getColour(swigCPtr), false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setMetricsMode(GuiMetricsMode gmm) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setMetricsMode(swigCPtr, (int)gmm);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public GuiMetricsMode getMetricsMode() {
    GuiMetricsMode ret = (GuiMetricsMode)OgreOverlayPINVOKE.PanelOverlayElementPtr_getMetricsMode(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setHorizontalAlignment(GuiHorizontalAlignment gha) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setHorizontalAlignment(swigCPtr, (int)gha);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public GuiHorizontalAlignment getHorizontalAlignment() {
    GuiHorizontalAlignment ret = (GuiHorizontalAlignment)OgreOverlayPINVOKE.PanelOverlayElementPtr_getHorizontalAlignment(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setVerticalAlignment(GuiVerticalAlignment gva) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setVerticalAlignment(swigCPtr, (int)gva);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public GuiVerticalAlignment getVerticalAlignment() {
    GuiVerticalAlignment ret = (GuiVerticalAlignment)OgreOverlayPINVOKE.PanelOverlayElementPtr_getVerticalAlignment(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool contains(float x, float y) {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_contains(swigCPtr, x, y);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isKeyEnabled() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_isKeyEnabled(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isCloneable() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_isCloneable(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCloneable(bool c) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setCloneable(swigCPtr, c);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public OverlayContainer getParent() {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_getParent(swigCPtr);
    OverlayContainer ret = (cPtr == global::System.IntPtr.Zero) ? null : new OverlayContainer(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void _setParent(OverlayContainer parent) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__setParent(swigCPtr, OverlayContainer.getCPtr(parent));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public ushort getZOrder() {
    ushort ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getZOrder(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getSquaredViewDepth(Camera cam) {
    float ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getSquaredViewDepth(swigCPtr, Camera.getCPtr(cam));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Ogre__Light_p_t getLights() {
    SWIGTYPE_p_std__vectorT_Ogre__Light_p_t ret = new SWIGTYPE_p_std__vectorT_Ogre__Light_p_t(OgreOverlayPINVOKE.PanelOverlayElementPtr_getLights(swigCPtr), false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public OverlayContainer castOverlayContainer() {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_castOverlayContainer(swigCPtr);
    OverlayContainer ret = (cPtr == global::System.IntPtr.Zero) ? null : new OverlayContainer(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PanelOverlayElement castPanelOverlayElement() {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_castPanelOverlayElement(swigCPtr);
    PanelOverlayElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new PanelOverlayElement(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public TextAreaOverlayElement castTextAreaOverlayElement() {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_castTextAreaOverlayElement(swigCPtr);
    TextAreaOverlayElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new TextAreaOverlayElement(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ParamDictionary getParamDictionary() {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_getParamDictionary__SWIG_0(swigCPtr);
    ParamDictionary ret = (cPtr == global::System.IntPtr.Zero) ? null : new ParamDictionary(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public StringList getParameters() {
    StringList ret = new StringList(OgreOverlayPINVOKE.PanelOverlayElementPtr_getParameters(swigCPtr), false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool setParameter(string name, string value) {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_setParameter(swigCPtr, name, value);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setParameterList(NameValueMap paramList) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setParameterList(swigCPtr, NameValueMap.getCPtr(paramList));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getParameter(string name) {
    string ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getParameter(swigCPtr, name);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void copyParametersTo(StringInterface dest) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_copyParametersTo(swigCPtr, StringInterface.getCPtr(dest));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void cleanupDictionary() {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_cleanupDictionary(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public Technique getTechnique() {
    global::System.IntPtr cPtr = OgreOverlayPINVOKE.PanelOverlayElementPtr_getTechnique(swigCPtr);
    Technique ret = (cPtr == global::System.IntPtr.Zero) ? null : new Technique(cPtr, false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ushort _getMaterialLodIndex() {
    ushort ret = OgreOverlayPINVOKE.PanelOverlayElementPtr__getMaterialLodIndex(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool preRender(SceneManager sm, RenderSystem rsys) {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_preRender(swigCPtr, SceneManager.getCPtr(sm), RenderSystem.getCPtr(rsys));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void postRender(SceneManager sm, RenderSystem rsys) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_postRender(swigCPtr, SceneManager.getCPtr(sm), RenderSystem.getCPtr(rsys));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public ushort getNumWorldTransforms() {
    ushort ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getNumWorldTransforms(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setUseIdentityProjection(bool useIdentityProjection) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setUseIdentityProjection(swigCPtr, useIdentityProjection);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getUseIdentityProjection() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getUseIdentityProjection(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setUseIdentityView(bool useIdentityView) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setUseIdentityView(swigCPtr, useIdentityView);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getUseIdentityView() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getUseIdentityView(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getCastsShadows() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getCastsShadows(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCustomParameter(uint index, Vector4 value) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setCustomParameter(swigCPtr, index, Vector4.getCPtr(value));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeCustomParameter(uint index) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_removeCustomParameter(swigCPtr, index);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool hasCustomParameter(uint index) {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_hasCustomParameter(swigCPtr, index);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector4 getCustomParameter(uint index) {
    Vector4 ret = new Vector4(OgreOverlayPINVOKE.PanelOverlayElementPtr_getCustomParameter(swigCPtr, index), false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void _updateCustomGpuParameter(GpuProgramParameters.AutoConstantEntry constantEntry, GpuProgramParameters params_) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr__updateCustomGpuParameter(swigCPtr, GpuProgramParameters.AutoConstantEntry.getCPtr(constantEntry), GpuProgramParameters.getCPtr(params_));
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setPolygonModeOverrideable(bool override_) {
    OgreOverlayPINVOKE.PanelOverlayElementPtr_setPolygonModeOverrideable(swigCPtr, override_);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getPolygonModeOverrideable() {
    bool ret = OgreOverlayPINVOKE.PanelOverlayElementPtr_getPolygonModeOverrideable(swigCPtr);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UserObjectBindings getUserObjectBindings() {
    UserObjectBindings ret = new UserObjectBindings(OgreOverlayPINVOKE.PanelOverlayElementPtr_getUserObjectBindings__SWIG_0(swigCPtr), false);
    if (OgreOverlayPINVOKE.SWIGPendingException.Pending) throw OgreOverlayPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
