//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class RaySceneQueryResult : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<RaySceneQueryResultEntry>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RaySceneQueryResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RaySceneQueryResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RaySceneQueryResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrePINVOKE.delete_RaySceneQueryResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public RaySceneQueryResult(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (RaySceneQueryResultEntry element in c) {
      this.Add(element);
    }
  }

  public RaySceneQueryResult(global::System.Collections.Generic.IEnumerable<RaySceneQueryResultEntry> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (RaySceneQueryResultEntry element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public RaySceneQueryResultEntry this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(RaySceneQueryResultEntry[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(RaySceneQueryResultEntry[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, RaySceneQueryResultEntry[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public RaySceneQueryResultEntry[] ToArray() {
    RaySceneQueryResultEntry[] array = new RaySceneQueryResultEntry[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<RaySceneQueryResultEntry> global::System.Collections.Generic.IEnumerable<RaySceneQueryResultEntry>.GetEnumerator() {
    return new RaySceneQueryResultEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new RaySceneQueryResultEnumerator(this);
  }

  public RaySceneQueryResultEnumerator GetEnumerator() {
    return new RaySceneQueryResultEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class RaySceneQueryResultEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<RaySceneQueryResultEntry>
  {
    private RaySceneQueryResult collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public RaySceneQueryResultEnumerator(RaySceneQueryResult collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public RaySceneQueryResultEntry Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (RaySceneQueryResultEntry)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    OgrePINVOKE.RaySceneQueryResult_Clear(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(RaySceneQueryResultEntry x) {
    OgrePINVOKE.RaySceneQueryResult_Add(swigCPtr, RaySceneQueryResultEntry.getCPtr(x));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = OgrePINVOKE.RaySceneQueryResult_size(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = OgrePINVOKE.RaySceneQueryResult_capacity(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    OgrePINVOKE.RaySceneQueryResult_reserve(swigCPtr, n);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public RaySceneQueryResult() : this(OgrePINVOKE.new_RaySceneQueryResult__SWIG_0(), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public RaySceneQueryResult(RaySceneQueryResult other) : this(OgrePINVOKE.new_RaySceneQueryResult__SWIG_1(RaySceneQueryResult.getCPtr(other)), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public RaySceneQueryResult(int capacity) : this(OgrePINVOKE.new_RaySceneQueryResult__SWIG_2(capacity), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  private RaySceneQueryResultEntry getitemcopy(int index) {
    RaySceneQueryResultEntry ret = new RaySceneQueryResultEntry(OgrePINVOKE.RaySceneQueryResult_getitemcopy(swigCPtr, index), true);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private RaySceneQueryResultEntry getitem(int index) {
    RaySceneQueryResultEntry ret = new RaySceneQueryResultEntry(OgrePINVOKE.RaySceneQueryResult_getitem(swigCPtr, index), false);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, RaySceneQueryResultEntry val) {
    OgrePINVOKE.RaySceneQueryResult_setitem(swigCPtr, index, RaySceneQueryResultEntry.getCPtr(val));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(RaySceneQueryResult values) {
    OgrePINVOKE.RaySceneQueryResult_AddRange(swigCPtr, RaySceneQueryResult.getCPtr(values));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public RaySceneQueryResult GetRange(int index, int count) {
    global::System.IntPtr cPtr = OgrePINVOKE.RaySceneQueryResult_GetRange(swigCPtr, index, count);
    RaySceneQueryResult ret = (cPtr == global::System.IntPtr.Zero) ? null : new RaySceneQueryResult(cPtr, true);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, RaySceneQueryResultEntry x) {
    OgrePINVOKE.RaySceneQueryResult_Insert(swigCPtr, index, RaySceneQueryResultEntry.getCPtr(x));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, RaySceneQueryResult values) {
    OgrePINVOKE.RaySceneQueryResult_InsertRange(swigCPtr, index, RaySceneQueryResult.getCPtr(values));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    OgrePINVOKE.RaySceneQueryResult_RemoveAt(swigCPtr, index);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    OgrePINVOKE.RaySceneQueryResult_RemoveRange(swigCPtr, index, count);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public static RaySceneQueryResult Repeat(RaySceneQueryResultEntry value, int count) {
    global::System.IntPtr cPtr = OgrePINVOKE.RaySceneQueryResult_Repeat(RaySceneQueryResultEntry.getCPtr(value), count);
    RaySceneQueryResult ret = (cPtr == global::System.IntPtr.Zero) ? null : new RaySceneQueryResult(cPtr, true);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    OgrePINVOKE.RaySceneQueryResult_Reverse__SWIG_0(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    OgrePINVOKE.RaySceneQueryResult_Reverse__SWIG_1(swigCPtr, index, count);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, RaySceneQueryResult values) {
    OgrePINVOKE.RaySceneQueryResult_SetRange(swigCPtr, index, RaySceneQueryResult.getCPtr(values));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
