//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum SceneBlendFactor {
  SBF_ONE,
  SBF_ZERO,
  SBF_DEST_COLOUR,
  SBF_SOURCE_COLOUR,
  SBF_ONE_MINUS_DEST_COLOUR,
  SBF_ONE_MINUS_SOURCE_COLOUR,
  SBF_DEST_ALPHA,
  SBF_SOURCE_ALPHA,
  SBF_ONE_MINUS_DEST_ALPHA,
  SBF_ONE_MINUS_SOURCE_ALPHA
}

}
