//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ScreenRatioPixelCountLodStrategy : PixelCountLodStrategyBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ScreenRatioPixelCountLodStrategy(global::System.IntPtr cPtr, bool cMemoryOwn) : base(OgrePINVOKE.ScreenRatioPixelCountLodStrategy_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ScreenRatioPixelCountLodStrategy obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrePINVOKE.delete_ScreenRatioPixelCountLodStrategy(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ScreenRatioPixelCountLodStrategy() : this(OgrePINVOKE.new_ScreenRatioPixelCountLodStrategy(), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public static ScreenRatioPixelCountLodStrategy getSingleton() {
    ScreenRatioPixelCountLodStrategy ret = new ScreenRatioPixelCountLodStrategy(OgrePINVOKE.ScreenRatioPixelCountLodStrategy_getSingleton(), false);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
