//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ShadowTextureListener : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ShadowTextureListener(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ShadowTextureListener obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ShadowTextureListener() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrePINVOKE.delete_ShadowTextureListener(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ShadowTextureListener() : this(OgrePINVOKE.new_ShadowTextureListener(), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void shadowTexturesUpdated(uint numberOfShadowTextures) {
    OgrePINVOKE.ShadowTextureListener_shadowTexturesUpdated(swigCPtr, numberOfShadowTextures);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void shadowTextureCasterPreViewProj(Light light, Camera camera, uint iteration) {
    OgrePINVOKE.ShadowTextureListener_shadowTextureCasterPreViewProj(swigCPtr, Light.getCPtr(light), Camera.getCPtr(camera), iteration);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void shadowTextureReceiverPreViewProj(Light light, Frustum frustum) {
    OgrePINVOKE.ShadowTextureListener_shadowTextureReceiverPreViewProj(swigCPtr, Light.getCPtr(light), Frustum.getCPtr(frustum));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool sortLightsAffectingFrustum(SWIGTYPE_p_std__vectorT_Ogre__Light_p_t lightList) {
    bool ret = OgrePINVOKE.ShadowTextureListener_sortLightsAffectingFrustum(swigCPtr, SWIGTYPE_p_std__vectorT_Ogre__Light_p_t.getCPtr(lightList));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
