//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum TexCoordCalcMethod {
  TEXCALC_NONE,
  TEXCALC_ENVIRONMENT_MAP,
  TEXCALC_ENVIRONMENT_MAP_PLANAR,
  TEXCALC_ENVIRONMENT_MAP_REFLECTION,
  TEXCALC_ENVIRONMENT_MAP_NORMAL,
  TEXCALC_PROJECTIVE_TEXTURE
}

}
