//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum TrackVertexColourEnum {
  TVC_NONE = 0x0,
  TVC_AMBIENT = 0x1,
  TVC_DIFFUSE = 0x2,
  TVC_SPECULAR = 0x4,
  TVC_EMISSIVE = 0x8
}

}
